runtime: python27
env: standard
threadsafe: true
api_version: 1

handlers:
# - url: /(.+)
#   static_files: app/\1
#   upload: app/.*

- url: /bootstrap
  static_dir: bootstrap

- url: .*
  # static_files: app/index.html
  # upload: app/index.html
  script: squadUp.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: MySQLdb
  version: "latest"

env_variables:
  CLOUDSQL_CONNECTION_NAME: squad-up-cc:australia-southeast1:squadup-sql
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: stxN}zk2zPC#7_[-